# Generated by Django 2.1.2 on 2018-11-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
